INITIAL_CUSTOMERS = [
    {
        "id": "CUST-001",
        "name": "Acme Corporation",
        "email": "billing@acme.com",
        "segment": "Enterprise",
        "clv": 145000,
        "retentionScore": 92,
        "loyaltyTier": "Platinum",
        "region": "North America",
        "tenureMonths": 48,
        "monthlySpend": 12500,
        "lastActive": "2026-07-06",
        "activityTrend": "Upward"
    },
    {
        "id": "CUST-002",
        "name": "Globex Industries",
        "email": "ops@globex.io",
        "segment": "Enterprise",
        "clv": 98000,
        "retentionScore": 45,
        "loyaltyTier": "Gold",
        "region": "Europe",
        "tenureMonths": 18,
        "monthlySpend": 9800,
        "lastActive": "2026-06-25",
        "activityTrend": "Declining"
    },
    {
        "id": "CUST-003",
        "name": "Initech LLC",
        "email": "accounting@initech.com",
        "segment": "Mid-Market",
        "clv": 42000,
        "retentionScore": 88,
        "loyaltyTier": "Silver",
        "region": "North America",
        "tenureMonths": 36,
        "monthlySpend": 3500,
        "lastActive": "2026-07-05",
        "activityTrend": "Stable"
    },
    {
        "id": "CUST-004",
        "name": "Umbrella Corp",
        "email": "procurement@umbrella.com",
        "segment": "Enterprise",
        "clv": 210000,
        "retentionScore": 78,
        "loyaltyTier": "Platinum",
        "region": "Europe",
        "tenureMonths": 60,
        "monthlySpend": 18500,
        "lastActive": "2026-07-03",
        "activityTrend": "Stable"
    },
    {
        "id": "CUST-005",
        "name": "Hooli Inc",
        "email": "gavin@hooli.xyz",
        "segment": "Enterprise",
        "clv": 165000,
        "retentionScore": 35,
        "loyaltyTier": "Platinum",
        "region": "APAC",
        "tenureMonths": 12,
        "monthlySpend": 15000,
        "lastActive": "2026-06-18",
        "activityTrend": "Declining"
    },
    {
        "id": "CUST-006",
        "name": "Soylent Corp",
        "email": "supply@soylent.com",
        "segment": "Mid-Market",
        "clv": 31000,
        "retentionScore": 68,
        "loyaltyTier": "Silver",
        "region": "LATAM",
        "tenureMonths": 14,
        "monthlySpend": 2800,
        "lastActive": "2026-07-01",
        "activityTrend": "Stable"
    },
    {
        "id": "CUST-007",
        "name": "Cyberdyne Systems",
        "email": "sarah@cyberdyne.ai",
        "segment": "Enterprise",
        "clv": 18000,
        "retentionScore": 94,
        "loyaltyTier": "Platinum",
        "region": "APAC",
        "tenureMonths": 24,
        "monthlySpend": 11000,
        "lastActive": "2026-07-07",
        "activityTrend": "Upward"
    },
    {
        "id": "CUST-008",
        "name": "Stark Industries",
        "email": "pepper@stark.com",
        "segment": "Enterprise",
        "clv": 350000,
        "retentionScore": 99,
        "loyaltyTier": "Platinum",
        "region": "North America",
        "tenureMonths": 72,
        "monthlySpend": 25000,
        "lastActive": "2026-07-07",
        "activityTrend": "Upward"
    },
    {
        "id": "CUST-009",
        "name": "Tyrell Corporation",
        "email": "replicant@tyrell.io",
        "segment": "Mid-Market",
        "clv": 55000,
        "retentionScore": 55,
        "loyaltyTier": "Gold",
        "region": "APAC",
        "tenureMonths": 10,
        "monthlySpend": 5500,
        "lastActive": "2026-06-29",
        "activityTrend": "Declining"
    },
    {
        "id": "CUST-010",
        "name": "Wayne Enterprises",
        "email": "bruce@wayne.co",
        "segment": "Enterprise",
        "clv": 290000,
        "retentionScore": 91,
        "loyaltyTier": "Platinum",
        "region": "North America",
        "tenureMonths": 54,
        "monthlySpend": 20000,
        "lastActive": "2026-07-06",
        "activityTrend": "Stable"
    },
    {
        "id": "CUST-011",
        "name": "Massive Dynamic",
        "email": "bell@massivedynamic.org",
        "segment": "Enterprise",
        "clv": 125000,
        "retentionScore": 82,
        "loyaltyTier": "Gold",
        "region": "Europe",
        "tenureMonths": 30,
        "monthlySpend": 10500,
        "lastActive": "2026-07-04",
        "activityTrend": "Stable"
    },
    {
        "id": "CUST-012",
        "name": "Wonka Industries",
        "email": "charlie@wonka.com",
        "segment": "SMB",
        "clv": 18000,
        "retentionScore": 74,
        "loyaltyTier": "Bronze",
        "region": "Europe",
        "tenureMonths": 8,
        "monthlySpend": 1800,
        "lastActive": "2026-07-02",
        "activityTrend": "Stable"
    },
    {
        "id": "CUST-013",
        "name": "Aperture Science",
        "email": "glados@aperture.edu",
        "segment": "Mid-Market",
        "clv": 49000,
        "retentionScore": 40,
        "loyaltyTier": "Silver",
        "region": "North America",
        "tenureMonths": 15,
        "monthlySpend": 4200,
        "lastActive": "2026-06-20",
        "activityTrend": "Declining"
    },
    {
        "id": "CUST-014",
        "name": "Dunder Mifflin",
        "email": "michael@dundermifflin.com",
        "segment": "SMB",
        "clv": 24000,
        "retentionScore": 79,
        "loyaltyTier": "Bronze",
        "region": "North America",
        "tenureMonths": 42,
        "monthlySpend": 2200,
        "lastActive": "2026-07-04",
        "activityTrend": "Stable"
    },
    {
        "id": "CUST-015",
        "name": "Gekko & Co",
        "email": "bud@gekko.com",
        "segment": "Mid-Market",
        "clv": 62000,
        "retentionScore": 86,
        "loyaltyTier": "Gold",
        "region": "LATAM",
        "tenureMonths": 20,
        "monthlySpend": 4800,
        "lastActive": "2026-07-05",
        "activityTrend": "Upward"
    }
]

INITIAL_PRODUCTS = [
    {
        "id": "PROD-001",
        "name": "KKVerse SaaS License Tier A",
        "category": "Software License",
        "price": 1500,
        "cost": 300,
        "stock": 9999,
        "minStockThreshold": 100,
        "warehouseLocation": "Cloud Server US-East",
        "status": "In Stock"
    },
    {
        "id": "PROD-002",
        "name": "KKVerse Core Database Node",
        "category": "Software License",
        "price": 3500,
        "cost": 700,
        "stock": 9999,
        "minStockThreshold": 50,
        "warehouseLocation": "Cloud Server EU-Central",
        "status": "In Stock"
    },
    {
        "id": "PROD-003",
        "name": "Enterprise Cloud Vault (50TB)",
        "category": "Cloud Storage",
        "price": 2500,
        "cost": 800,
        "stock": 500,
        "minStockThreshold": 50,
        "warehouseLocation": "S3 Virginia Cluster",
        "status": "In Stock"
    },
    {
        "id": "PROD-004",
        "name": "AI Copilot Integration Suite",
        "category": "Software License",
        "price": 5000,
        "cost": 1200,
        "stock": 9999,
        "minStockThreshold": 200,
        "warehouseLocation": "Cloud Server Tokyo",
        "status": "In Stock"
    },
    {
        "id": "PROD-005",
        "name": "Quantum BI Gateway Server v4",
        "category": "Hardware",
        "price": 12500,
        "cost": 6500,
        "stock": 14,
        "minStockThreshold": 15,
        "warehouseLocation": "Warehouse West SF",
        "status": "Low Stock"
    },
    {
        "id": "PROD-006",
        "name": "Business Intelligence On-Site Setup",
        "category": "Consulting",
        "price": 8000,
        "cost": 3000,
        "stock": 100,
        "minStockThreshold": 10,
        "warehouseLocation": "On-site Delivery",
        "status": "In Stock"
    },
    {
        "id": "PROD-007",
        "name": "Edge Compute Gateway Module",
        "category": "Hardware",
        "price": 4500,
        "cost": 2100,
        "stock": 3,
        "minStockThreshold": 10,
        "warehouseLocation": "Warehouse East NY",
        "status": "Low Stock"
    },
    {
        "id": "PROD-008",
        "name": "Platinum Dedicated Engineer SLA",
        "category": "Support",
        "price": 12000,
        "cost": 5000,
        "stock": 25,
        "minStockThreshold": 5,
        "warehouseLocation": "Remote Support Team",
        "status": "In Stock"
    },
    {
        "id": "PROD-009",
        "name": "Standard IoT Sync Station",
        "category": "Hardware",
        "price": 3200,
        "cost": 1400,
        "stock": 0,
        "minStockThreshold": 12,
        "warehouseLocation": "Warehouse West SF",
        "status": "Out of Stock"
    }
]

INITIAL_SALES = [
    {
        "id": "SALE-001",
        "customerId": "CUST-001",
        "customerName": "Acme Corporation",
        "productId": "PROD-004",
        "productName": "AI Copilot Integration Suite",
        "quantity": 2,
        "totalRevenue": 10000,
        "totalCost": 2400,
        "profit": 7600,
        "saleDate": "2026-01-15",
        "region": "North America",
        "salesRep": "Elena Rostova"
    },
    {
        "id": "SALE-002",
        "customerId": "CUST-003",
        "customerName": "Initech LLC",
        "productId": "PROD-001",
        "productName": "KKVerse SaaS License Tier A",
        "quantity": 5,
        "totalRevenue": 7500,
        "totalCost": 1500,
        "profit": 6000,
        "saleDate": "2026-01-20",
        "region": "North America",
        "salesRep": "John Vance"
    },
    {
        "id": "SALE-003",
        "customerId": "CUST-002",
        "customerName": "Globex Industries",
        "productId": "PROD-002",
        "productName": "KKVerse Core Database Node",
        "quantity": 1,
        "totalRevenue": 3500,
        "totalCost": 700,
        "profit": 2800,
        "saleDate": "2026-02-11",
        "region": "Europe",
        "salesRep": "Sarah Jenkins"
    },
    {
        "id": "SALE-004",
        "customerId": "CUST-004",
        "customerName": "Umbrella Corp",
        "productId": "PROD-008",
        "productName": "Platinum Dedicated Engineer SLA",
        "quantity": 1,
        "totalRevenue": 12000,
        "totalCost": 5000,
        "profit": 7000,
        "saleDate": "2026-02-28",
        "region": "Europe",
        "salesRep": "Sarah Jenkins"
    },
    {
        "id": "SALE-005",
        "customerId": "CUST-008",
        "customerName": "Stark Industries",
        "productId": "PROD-005",
        "productName": "Quantum BI Gateway Server v4",
        "quantity": 3,
        "totalRevenue": 37500,
        "totalCost": 19500,
        "profit": 18000,
        "saleDate": "2026-03-05",
        "region": "North America",
        "salesRep": "Elena Rostova"
    },
    {
        "id": "SALE-006",
        "customerId": "CUST-007",
        "customerName": "Cyberdyne Systems",
        "productId": "PROD-004",
        "productName": "AI Copilot Integration Suite",
        "quantity": 1,
        "totalRevenue": 5000,
        "totalCost": 1200,
        "profit": 3800,
        "saleDate": "2026-03-22",
        "region": "APAC",
        "salesRep": "Kenji Sato"
    },
    {
        "id": "SALE-007",
        "customerId": "CUST-010",
        "customerName": "Wayne Enterprises",
        "productId": "PROD-003",
        "productName": "Enterprise Cloud Vault (50TB)",
        "quantity": 4,
        "totalRevenue": 10000,
        "totalCost": 3200,
        "profit": 6800,
        "saleDate": "2026-04-02",
        "region": "North America",
        "salesRep": "John Vance"
    },
    {
        "id": "SALE-008",
        "customerId": "CUST-005",
        "customerName": "Hooli Inc",
        "productId": "PROD-006",
        "productName": "Business Intelligence On-Site Setup",
        "quantity": 1,
        "totalRevenue": 8000,
        "totalCost": 3000,
        "profit": 5000,
        "saleDate": "2026-04-18",
        "region": "APAC",
        "salesRep": "Kenji Sato"
    },
    {
        "id": "SALE-009",
        "customerId": "CUST-011",
        "customerName": "Massive Dynamic",
        "productId": "PROD-001",
        "productName": "KKVerse SaaS License Tier A",
        "quantity": 8,
        "totalRevenue": 12000,
        "totalCost": 2400,
        "profit": 9600,
        "saleDate": "2026-05-09",
        "region": "Europe",
        "salesRep": "Sarah Jenkins"
    },
    {
        "id": "SALE-010",
        "customerId": "CUST-001",
        "customerName": "Acme Corporation",
        "productId": "PROD-005",
        "productName": "Quantum BI Gateway Server v4",
        "quantity": 1,
        "totalRevenue": 12500,
        "totalCost": 6500,
        "profit": 6000,
        "saleDate": "2026-05-27",
        "region": "North America",
        "salesRep": "Elena Rostova"
    },
    {
        "id": "SALE-011",
        "customerId": "CUST-015",
        "customerName": "Gekko & Co",
        "productId": "PROD-002",
        "productName": "KKVerse Core Database Node",
        "quantity": 2,
        "totalRevenue": 7000,
        "totalCost": 1400,
        "profit": 5600,
        "saleDate": "2026-06-12",
        "region": "LATAM",
        "salesRep": "Mateo Garcia"
    },
    {
        "id": "SALE-012",
        "customerId": "CUST-008",
        "customerName": "Stark Industries",
        "productId": "PROD-004",
        "productName": "AI Copilot Integration Suite",
        "quantity": 5,
        "totalRevenue": 25000,
        "totalCost": 6000,
        "profit": 19000,
        "saleDate": "2026-06-28",
        "region": "North America",
        "salesRep": "Elena Rostova"
    },
    {
        "id": "SALE-013",
        "customerId": "CUST-004",
        "customerName": "Umbrella Corp",
        "productId": "PROD-001",
        "productName": "KKVerse SaaS License Tier A",
        "quantity": 10,
        "totalRevenue": 15000,
        "totalCost": 3000,
        "profit": 12000,
        "saleDate": "2026-07-02",
        "region": "Europe",
        "salesRep": "Sarah Jenkins"
    },
    {
        "id": "SALE-014",
        "customerId": "CUST-006",
        "customerName": "Soylent Corp",
        "productId": "PROD-003",
        "productName": "Enterprise Cloud Vault (50TB)",
        "quantity": 2,
        "totalRevenue": 5000,
        "totalCost": 1600,
        "profit": 3400,
        "saleDate": "2026-07-04",
        "region": "LATAM",
        "salesRep": "Mateo Garcia"
    },
    {
        "id": "SALE-015",
        "customerId": "CUST-007",
        "customerName": "Cyberdyne Systems",
        "productId": "PROD-008",
        "productName": "Platinum Dedicated Engineer SLA",
        "quantity": 2,
        "totalRevenue": 24000,
        "totalCost": 10000,
        "profit": 14000,
        "saleDate": "2026-07-06",
        "region": "APAC",
        "salesRep": "Kenji Sato"
    }
]

INITIAL_USER = {
    "name": "Alexander Vance",
    "email": "kanith770@gmail.com",
    "role": "Chief Business Intelligence Officer (CBIO)",
    "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    "company": "KKVerse Global Inc.",
    "department": "Executive Strategy & Analytics"
}

CHURN_FEATURES = [
    {"name": "Monthly Spend Ratio", "importance": 0.28, "desc": "Normalized monthly spend relative to industry sector"},
    {"name": "Tenure Duration (Months)", "importance": 0.22, "desc": "Time elapsed since first license validation"},
    {"name": "Support Ticket Urgency Score", "importance": 0.18, "desc": "Frequency and average response delay of unresolved critical tickets"},
    {"name": "Sync Node Heartbeat Integrity", "importance": 0.15, "desc": "Ping consistency of connected on-premise components"},
    {"name": "Activity Drift Index", "importance": 0.11, "desc": "Weekly change in software utilization patterns"},
    {"name": "Regional Sales Rep Tenure", "importance": 0.06, "desc": "Experience levels of local customer success rep"}
]

BUSINESS_SCORE_COMPONENTS = [
    {"name": "Revenue Yield Strategy", "score": 94, "weight": 0.3, "description": "Year-on-year growth trajectory and expansion ratios"},
    {"name": "Client Asset Integrity", "score": 82, "weight": 0.25, "description": "Customer retention index and loyal user base lifetime value"},
    {"name": "Asset Liquidity & Inventory Velocities", "score": 88, "weight": 0.2, "description": "Rate of software seat validation and hardware module flow"},
    {"name": "AI Automation Multiplier", "score": 91, "weight": 0.15, "description": "System suggestions adoption rate and automated ticket closures"},
    {"name": "Operational Capital Margin", "score": 86, "weight": 0.1, "description": "Profit margin optimizations against overhead server allocations"}
]
